name: Build

on:
  push:
    branches:
      - "main"

jobs:
  # Build image
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mamba: [latest, 1.4.0]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "./"
          file: "./Dockerfile"
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/micromamba:${{ matrix.mamba }}
          build-args: |
            MAMBA_VERSION=${{ matrix.mamba }}

  # Build CUDA image for Ubuntu 20.04/22.04
  build-cuda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mamba: [latest, 1.4.0]
        cuda: [11.8.0, 12.5.0]
        flavor: [runtime, devel]
        ubuntu: [20.04, 22.04]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare image tag
        run: |
          IFS='.' read -r -a cuda <<< "${{ matrix.cuda }}"
          echo "cuda=cu${cuda[0]}${cuda[1]}" >> $GITHUB_ENV
      - name: Build cuda image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: "./"
          file: "./Dockerfile.cuda"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/micromamba:${{ matrix.mamba }}-${{ env.cuda }}-${{ matrix.flavor }}-ubuntu${{ matrix.ubuntu }}
          build-args: |
            MAMBA_VERSION=${{ matrix.mamba }}
            CUDA=${{ matrix.cuda }}
            FLAVOR=${{ matrix.flavor }}
            UBUNTU=${{ matrix.ubuntu }}
